samples: 
        - MPI-025
        - MPI-048
        - MPI-051
        - MPI-061
        - MPI-065
        - MPI-242
        - MPI-296
        - MPI-318
        - MPI-333
        - MPI-334
        - MPI-335
        - MPI-336
        - MPI-345
        - MPI-369
        - MPI-376
        - MPI-378
        - MPI-379
        - MPI-381Batch1
        - MPI-381Batch3
        - MPI-383
        - MPI-389
        - MTW-MDB-001
        - MTW-MDB-002
        - MTW-MDB-003
        - MTW-MDB-009
        - MTW-MDB-011
        - MTW-MDB-014
        - MTW-MDB-015
        - MTW-MDB-016
        - MTW-MDB-019
        - MTW-MDB-020
        - MTW-MDB-024
        - MTW-MDB-025
        - MTW-MDB-026
        - MTW-MDB-028
        - MTW-MDB-032
        - MTW-MDB-034
        - MTW-MDB-035
        - MTW-TLL-002
        - MTW-TLL-006
        - MTW-TLL-007
        - MTW-TLL-008
        - MTW-TLL-010
        - MTW-TLL-011
        - MTW-TLL-012
        - MTW-TLL-013Batch2
        - MTW-TLL013Batch3
        - MTW-TLL-016
        - MTW-TLL-017
        - MTW-TLL-019
        - MTW-TLL-020
        - MTW-TLL-021
        - MTW-TLL-022
        - MTW-TLL-023
        - MTW-TLL-024
        - MTW-TLL-025
        - MTW-TLL-026
        - MTW-TLL-027
        - MTW-TLL-029
        - MTW-TLL-030
        - MTW-TLL-032
        - MTW-TLL-034
        - MTW-TLL-035
        - MTW-TLL-037
        - MTW-TLL-038
        - MTW-TLL-039
        - MTW-TLL-040
        - MTW-TLL-041
        - MTW-TLL-042
        - MTW-TLL-043
        - SMB-ANK-003
        - SMB-ANK-004
        - SMB-ANK-005
        - SMB-ANK-006
        - SMB-ANK-007
        - SMB-ANK-009
        - SMB-ANK-011
        - SMB-ANK-013
        - SMB-ANK-015
        - SMB-ANK-016Batch2
        - SMB-ANK016Batch3
        - SMB-ANK-019
        - SMB-ANK-024
        - SMB-ANK-026
        - SMB-ANK-027Batch1
        - SMB-ANK-027Batch2
        - SMB-ANK027Batch3
        - SMB-ANK-028
        - SMB-ANK-029
        - SMB-ANK-030
        - SMB-BKB008
        - SMB-HPM006
        - SMB-HPM016
        - SMB-HPM018
        - SMB-HPM021
        - SMB-HPM027
        - SMB-PDT001
        - SMB-PDT007
        - SMB-PDT036
        - SMB-PTB028
        - SMB-RIN003
        - SMB-RIN009
        - SMB-RIN014
        - SMB-RIN016
        - SMB-RIN019
        - SMB-WHB024
        - SMB-WNG-001
        - SMB-WNG-002
        - SMB-WNG-003
        - SMB-WNG-004
        - SMB-WNG-006
        - SMB-WNG-007
        - SMB-WNG-009
        - SMB-WNG-012
        - SMB-WNG-014
        - SMB-WNG-017
        - SMB-WNG-018
        - SMB-WNG-020
        - SMB-WNG-021Batch1
        - SMB-WNG021Batch3
        - SMB-WNG-022
        - SMB-WNG-023
        - SMB-WNG-028
